version: '3.7'

services:

  sample:
    container_name: book-library-react-front-end
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/src'
      - './node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
